/*
 * DO NOT MODIFY. This file is automatically generated during the pre-build
 *                step by the lib_search utility
 */

"E:\BeelinkerCode\simple_peripheral\blelib\host\host_pxxx.a"
"E:\BeelinkerCode\simple_peripheral\blelib\ctrl\cc2640\cc2640_ctrl_pxxx.a"
"E:\BeelinkerCode\simple_peripheral\blelib\hci_tl\cc26xx\cc26xx_hci_tl_none.a"
